// Script para extrair configurações do localStorage
console.log('=== EXTRATOR DE CONFIGURAÇÕES ===');
console.log('\nPara extrair suas alterações:');
console.log('1. Abra http://localhost:5001 no navegador');
console.log('2. Pressione F12 para abrir DevTools');
console.log('3. Vá para a aba Console');
console.log('4. Execute este comando:');
console.log('\n--- COPIE E COLE NO CONSOLE DO NAVEGADOR ---');
console.log('\n// Extrair configurações atuais');
console.log('const siteContent = localStorage.getItem(\'site_content\');');
console.log('if (siteContent) {');
console.log('  const config = JSON.parse(siteContent);');
console.log('  ');
console.log('  console.log(\'=== SUAS ALTERAÇÕES ===\');');
console.log('  ');
console.log('  // Verificar títulos');
console.log('  if (config.titleBlocks) {');
console.log('    console.log(\'\\n📝 TÍTULOS ALTERADOS:\');');
console.log('    Object.keys(config.titleBlocks).forEach(key => {');
console.log('      console.log(`${key}: "${config.titleBlocks[key]}"`);');
console.log('    });');
console.log('  }');
console.log('  ');
console.log('  // Verificar cores dos CTAs');
console.log('  if (config.customCTAs) {');
console.log('    console.log(\'\\n🎨 CORES DOS BOTÕES:\');');
console.log('    if (config.customCTAs.doctorTrustCTA) {');
console.log('      console.log(\'Doctor Trust CTA:\', config.customCTAs.doctorTrustCTA.backgroundColor);');
console.log('    }');
console.log('    if (config.customCTAs.successStoryCTA) {');
console.log('      console.log(\'Success Story CTA:\', config.customCTAs.successStoryCTA.backgroundColor);');
console.log('    }');
console.log('  }');
console.log('  ');
console.log('  // Verificar cores de fundo');
console.log('  if (config.backgroundSettings) {');
console.log('    console.log(\'\\n🌈 CORES DE FUNDO:\');');
console.log('    console.log(\'Background atual:\', config.backgroundSettings.currentBackground);');
console.log('  }');
console.log('  ');
console.log('  // Salvar configuração completa para análise');
console.log('  console.log(\'\\n💾 CONFIGURAÇÃO COMPLETA (copie este JSON):\');');
console.log('  console.log(JSON.stringify(config, null, 2));');
console.log('  ');
console.log('} else {');
console.log('  console.log(\'❌ Nenhuma configuração encontrada no localStorage\');');
console.log('}');

console.log('\n--- FIM DO COMANDO ---\n');
console.log('5. Copie o resultado e me envie para que eu possa aplicar como padrão');
console.log('\nOu execute: node extract-changes.js > config-atual.json');